language: node_js
node_js:
  - "6"
  - "5"
  - "4"

env:
  - CXX=g++-4.8
  
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8

compiler: gcc
sudo: false

os:
  - linux
  - osx
    osx_image: xcode7.3

before_install:
  - node --version
  - npm --version
  - gcc --version

script:
  - npm install

cache:
  directories:
    - $HOME/.node-gyp
    - $HOME/.npm
    - node_modules
