language: node_js
node_js:
  - "6"
  - "5"
  - "4"

env:
  - CXX=clang++-3.6
  
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
      - clang-3.6

compiler: clang
sudo: false

os:
  - linux
  - os: osx

before_install:
  - node --version
  - npm --version
  - gcc --version

script:
  - npm install

cache:
  directories:
    - $HOME/.node-gyp
    - $HOME/.npm
    - node_modules
